### ISSUE TITLE
Troubleshooting: API call for data

### ISSUE THREAD

**Issue by hwerman** [hwerman/grtgProject#1]
1. Looking through the API documentation and exploring with the API on Postman, it appears that the soundtrack information for each movie is referenced per song - a distinct url for each song within the object as follows:
   { movies: [
   {each movie}
   {each movie}
   ]
   and then within each movie:
   { 'songs': [
   {each song info w distinct url}
   {each song info w distinct url}
   {each song info w distinct url}
   ]

I'm aiming to list all songs for one movie with one fetch, following the fetch to get all movies. I'm also having an issue with the fetch call for all movies because even though the API provides a formula for calling all movies (which is currently working successfully for me), I'm trying to set up a fetch call since I'll need the second fetch call immediately following the all movie search for the soundtrack search. The API doesn't consistently reference the movies either - so some urls are .../movie/nameOfMovie-year and some are .../movie/nameOfMovie 

Three attempts at fixing the issue:
- Fetch call with the $req.query params given in Postman
- Using Postman to try to access the songs specifically
- Getting the urls to render on the page (but not helpful)

**Comment by hwerman** [comment]
@gittheking @jasonseminar @rapala61 @irwintsay @trevorpreston

**Comment by hwerman** [comment]
@jasonseminara

**Comment by irwintsay** [comment]
Looks like you figured it out!

**Comment by hwerman** [comment]
yaassss. thanks @irwintsay a mil
